name: Deploy Storybook to Chromatic

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Allow one concurrent deployment
concurrency:
  group: "chromatic"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: windows-latest
    steps:
      - name: Warn missing Chromatic configuration
        env: 
            super_secret: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        if: ${{ env.super_secret == '' }}
        run: |
          echo "Please add your project to chromatic and configure the CHROMATIC_PROJECT_TOKEN secret"
          exit -1
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Refresh Types
        run: npm run refreshTypes 
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

